config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/logout' => 'sessions#destroy', as: :logout
  get 'signup' => 'users#new', as: :signup
  resources :sessions, only: [:new, :create]

  delete 'users/:id' => 'users#destroy', as: :users_destroy
  get 'users/index' => 'users#index', as: :search_users
  resources :users

  get 'boards/show' => 'boards#show', as: :public_boards
  delete 'boards/:id' => 'boards#destroy', as: :boards_destroy
  get 'boards/index' => 'boards#index', as: :search_boards
  resources :boards
  get 'boards/:id/private' => 'boards#makePrivate', as: :make_board_private
  get 'boards/:id/updateBoard' => 'boards#editInfo', as: :edit_board_info
  patch 'boards/:id/updateBoard' => 'boards#updateInfo', as: :update_board_info

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  mount_uploader :title #image_uploader

  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("LOWER(tag_list) like ?", "%#{query.downcase}%") 
  end
end

app/models/image_uploader.rb
class ImageUploader < CarrierWave::Uploader::Base
 
  include CarrierWave::MiniMagick
 
  storage :file
 
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end
 
  version :thumb, :from_version => :medium do
    process resize_to_fit: [100, 100]
  end
 
  version :square do
    process :resize_to_fill => [500, 500]
  end
 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :boards
  accepts_nested_attributes_for :boards

  #validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("LOWER(name) like ?", "%#{query.downcase}%") 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :authorize

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end

end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authorize

  #@user = current_user
  require 'base64'
  require 'fileutils'
  #require 'mini_magick'
  skip_before_filter :verify_authenticity_token

  #before_action :authorize, only:[:new]

  def index
     if params[:search]
       @board = Board.tagged_with(params[:search]).order("created_at DESC")
     else
       @boards = Board.order("created_at DESC")
     end
  end

  def show
   @boards = Board.all
  end

  def new
    @board = Board.new
  end

  # protect_from_forgery

  def create
    # CHECK IF BOARD IS BEING UPDATED OR CREATED
    @update_board = @board ? true : false
    if @update_board # if board is being updated
      @board = Board.find(params[:id])
      @img_path = Boards.imagepath + ".png"
    else # if board brand new
      @board = current_user.boards.new()
      @img_path = current_user.id.to_s + "_" + Time.now.strftime("%d%m%Y%h%M%S") + "_" + (0...16).map {('a'..'z').to_a[rand(26)] }.join
    end
    # Proceed to Update or Create new board
    File.open("#{Rails.root}/public/images/#{@img_path}.png", 'wb') do |f|
      f.write(params[:image].read)
    end
    #@board = Board.new
    # Declare Image Attributes
    @board.imagepath = @img_path + ".png"
    img = MiniMagick::Image.open("#{Rails.root}/public/images/#{@img_path}.png")
    #src_file = File.open("#{Rails.root}/public/images/#{@img_path}.png")
    #puts src_file.to_s
    #uploader = ImageUploader.new
    #uploader.store!(params[:image])
    @board.title = File.open("#{Rails.root}/public/images/#{@img_path}.png")  
    @board.width = img.width
    @board.height = img.height
    @board.likes = 0
    @board.private = false
    if @board.save
      #redirect_to edit_board_path(@board)
      flash[:success] = "White Board Saved Son!"
    else
      flash[:failure] = "Oops, There was a problem...Please Try again later."
    end
  end

  def edit
    #logger.debug Board.find(params[:id])
    @board = Board.find(params[:id])
    if @board.private == true and current_user.id != @board.user.id 
      redirect_to user_path(current_user)
    end
    data = open(@board.title.to_s)
    File.open("#{Rails.root}/public/images/#{@board.imagepath}.png", "wb") { |f|
        f.write(data.read)
    }
  end

  def update
    @board = Board.find(params[:id])
    @img_path = current_user.id.to_s + Time.now.strftime("%d%m%Y%h%M%S") + "_" + (0...16).map {('a'..'z').to_a[rand(26)] }.join
    #logger.debug @img_path
    File.open("#{Rails.root}/public/images/#{@img_path}.png", "wb") { |f|
        f.write(params[:image].read)
    }
    #if File.exists?("#{Rails.root}/public/images/#{@board.imagepath}")
      #FileUtils.rm("#{Rails.root}/public/images/#{@board.imagepath}")
    #end
    @board.title = File.open("#{Rails.root}/public/images/#{@img_path}.png")
    @board.imagepath = @img_path
    if @board.save
      #redirect_to(:back)
    end
  end

  def destroy
    @board = Board.find(params[:id])
    if File.exists?("#{Rails.root}/public/images/#{@board.imagepath}")
      FileUtils.rm("#{Rails.root}/public/images/#{@board.imagepath}")
    end
    if @board.destroy
      return
    end
  end

  def makePrivate
    @board = Board.find(params[:id])
    if @board.private
      @board.private = false;
    else
      @board.private = true;
    end
    if @board.save
      redirect_to(:back)
    end
  end

  def editInfo
    @board = Board.find(params[:id])
  end

  def updateInfo
    @board = Board.find(params[:id])
    @board.update_attributes(board_params)   
    if @board.save
      redirect_to(:back)
    end
  end

  private
    def board_params
      params.require(:board).permit(:tag_list)
    end
#Controller Ending
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by({email: params[:email]})
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Welcome #{@user.name}. You are now logged in!"
      redirect_to user_path @user
    else
      flash[:fail] = "Oops, wrong email password combination."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only:[:show, :edit,:update, :destroy]  
  before_action :logged_in?, only:[:show,:edit,:update,:destroy]

  def index
     if params[:search]
       @users = User.search(params[:search]).order("created_at DESC")
     else
       @users = User.order("created_at DESC")
     end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path @user
    else
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path @user
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to boards_path
    end
  end

  private
    def user_params 
      params.require(:user).permit(:email, :password, :name, :about)  
    end    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/create.html.erb
<h1>Boards#create</h1>
<p>Find me in app/views/boards/create.html.erb</p>

app/views/boards/create.js.erb
console.log('it works');

app/views/boards/destroy.html.erb
<h1>Boards Destroy</h1>

app/views/boards/edit.html.erb
<%= image_tag @board.imagepath.to_s + ".png", id:"image_to_canvas" %>
<!--<img src= '<#%= @board.title.to_s %>' id="image_to_canvas" sourcing='<#%= @board.title.to_s %>' >-->
<div id="divLoading"></div>
<div id="image_box">
<br>
<hr>
<h1> Use + and - To Adjust the Height and Width </h1>
<br><br>
<h1> Up and Down Arrow Keys: Adjust the Height </h1>
<h1> Left and Right Arrow Keys: Adjust the Width </h1>
<hr>
<br><br>
<hr>
<h1> Click To Place The Image </h1>
<hr>
</div>
<img src='' id='forUploads'>

app/views/boards/editInfo.html.erb
<div id="divLoading"></div>
<div id="float-form">
<button class="index_profile_button"><%= link_to 'My Profile', users_path + "/" + current_user.id.to_s %><div class="fa fa-lg fa-child"></div></button>

<h1>Edit Board Tags</h1>
<%= form_for @board, url: update_board_info_path(@board)  do |f| %>
    <fieldset>
      <div class="form-group">
          <%= f.label :tags, 'Tags Example: cool, bird, outside', class: 'col-md-4 control-label' %>
          <hr>
        <div class="col-md-5">
            <%= f.text_area :tag_list, rows:"5", cols:"50", maxlength: '100', class: 'form-control', style: "font-size: 18px; color: darkblue" %>
        </div>
      </div>
      <div class="form-group">
          <div class="col-md-8 col-md-offset-4">
              <%= f.submit 'Update Tags', class: 'btn btn-success', style: "font-size: 17px; font-weight: bold; color: darkblue; width: 180px; height:40px; cursor: pointer; border: 3px outset black; background-color: white" %>
          </div>
      </div>
    </fieldset>
<% end %>
<%= image_tag @board.title.to_s, id: 'edit_img_tags' %>

</div>

app/views/boards/index.html.erb
<div style="overflow: auto" id="float-form">
  <button class="index_profile_button"><%= link_to 'My Profile', users_path + "/" + current_user.id.to_s %><div class="fa fa-lg fa-child"></div></button>
  <button style="width:290px; color:darkgreen" class="index_profile_button"><%= link_to 'Recent Public Boards', public_boards_path %><div class="fa fa-lg fa-file-picture-o"></div></button>
  <h1>Search for Public Boards</h1>
  <hr>
  <%= form_tag(search_boards_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Boards", style:"font-size:20px;" %>
    <button id="index_search_button" type="submit"><i class="fa fa-lg fa-search"></i></button>
  <% end %><hr>

<% @board.each do |b| %>
  <% if b.private == false %>
  <div class="user">
    <h2 style=""><%= link_to "| Board Owner: " + b.user.name+ " |", user_path(b.user) %></h2>
    <%= image_tag b.title.to_s, id: 'index_img_view' %><br>
            <button class="index_button"><a class="btn btn-md btn-primary" href=<%= '/boards/'+ b.id.to_s + '/edit' %>>Edit Board <div class="fa fa-lg fa-paint-brush"></div></a></button><br></br>
  </div>
  <hr>
  <% end %>
<% end %>
</div>

app/views/boards/new.html.erb
<div id="image_box">
<br>
<hr>
<h1> Use + and - To Adjust the Height and Width </h1>
<br><br>
<h1> Up and Down Arrow Keys: Adjust the Height </h1>
<h1> Left and Right Arrow Keys: Adjust the Width </h1>
<hr>
<br><br>
<hr>
<h1> Click To Place The Image </h1>
<hr>
</div>

app/views/boards/show.html.erb
<div style="overflow: auto" id="float-form">
  <button class="index_profile_button"><%= link_to 'My Profile', users_path + "/" + current_user.id.to_s %><div class="fa fa-lg fa-child"></div></button>
  <button style="width:290px; color:darkgreen" class="index_profile_button"><%= link_to 'Recent Public Boards', public_boards_path %><div class="fa fa-lg fa-file-picture-o"></div></button>
  <h1>Recent Public Boards</h1>
  <hr>
  <%= form_tag(search_boards_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
    <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Boards", style:"font-size:20px;" %>
    <button id="index_search_button" type="submit"><i class="fa fa-lg fa-search"></i></button>
  <% end %><hr>

<% @boards.reverse.each do |b| %>
  <% if b.private == false and !(b.title.to_s == "") %>
  <div class="user">
    <%= image_tag b.title.to_s, id: 'index_img_view' %><br>
            <button class="index_button"><a class="btn btn-md btn-primary" href=<%= '/boards/'+ b.id.to_s + '/edit' %>>Edit Board <div class="fa fa-lg fa-paint-brush"></div></a></button><br></br>
  </div>
  <hr>
  <% end %>
<% end %>
</div>

app/views/boards/update.html.erb
<h1>Boards#update</h1>
<p>Find me in app/views/boards/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhiteboardCentral</title>
  <%= stylesheet_link_tag    'users', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>

<% if flash[:success] %>
    <div class="alert alert-success"><%= flash[:success] %></div>
<% elsif flash[:fail] %>
    <div class="alert alert-warning"><%= flash[:fail] %></div>
<% end %>
<script>$('.alert').delay(2100).slideUp()</script>

<%= yield %>

</body>
</html>

app/views/layouts/boards.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhiteboardCentral</title>
  <%= stylesheet_link_tag    'boards', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body data-no-turbolink="no">
<div id="toolbar">
    <div id="free"><input class='simple_color_kitchen_sink' value='#00000'/></div> <div id="colors">
  </div>

    <div id="rad">
      BrushSize <span id="radval">10</span>
      <div id="decrad" class="radcontrol"><i class="fa fa-minus"></i></div>
      <div id="incrad" class="radcontrol"><i class="fa fa-plus"></i></div>
    </div>
    <button class="buttonOnBoard" id="eraser"><i class="fa fa-lg fa-eraser"></i></button>
    <button id="save" class="fa fa-lg buttonOnBoard ">Save</button>
    <button id="clear">Clear</button>
      <% if logged_in? %>
        <%= link_to 'Logout', logout_path, :class => "buttonOnBoard" %>
      <% else %>
        <%= link_to 'Login', new_session_path, :class => "buttonOnBoard" %>
      <% end %>
      <%= link_to 'Profile', users_path + "/" + current_user.id.to_s, :class => "buttonOnBoard" %>
    <input type='file' id="fileUpload" />
  </div>
  <canvas id="canvas" style="display:block;width:100%;height:95%">
  Browser is incompatiable.
  </canvas>

  </div>

<%= yield %>
<%= javascript_include_tag 'boards', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'simplecolor', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users</h1>
<% @users.each do |user| %>
  <div class="user">
    <h1 class="user-title"><%= link_to user.title, user %></h1>
    <p class="user-content"><%= user.content %></p>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Users That Match Your Search</h1>
<% @users.each do |user| %>
  <div class="user">
    <h1 class="user-title">| <%= link_to user.name, user %> |</h1>
  </div>
  <hr>
<% end %>

app/views/users/new.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">- WhiteBoard-Central -</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <% if current_user %>
                      <%= link_to '- Profile -', users_path + "/" + current_user.id.to_s %>
                    <% else %>
                      <%= link_to "- Create Account -", new_user_path %>
                    <% end %>
                </li>
                <li>
                    <% if current_user %>
                      <%= link_to '- Logout -', logout_path %>
                    <% else %>
                      <%= link_to '- Login -', new_session_path %>
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<%= form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
  <hr>
  <%= f.label :name, 'Name', :html => {:class => 'control-label'}, :style => 'font-size: 18px; margin-left: 16px' %> <i class="fa fa-lg fa-star bg bg-warning"></i>
  <%= f.text_field :name, :class => 'form-control', :style => 'max-width: 300px; margin-left:16px' %> <br><br>
  <%= f.label :email, 'Email', :html => {:class => 'control-label'}, :style => 'font-size: 18px; margin-left: 16px' %> <i class="fa fa-lg fa-star bg bg-warning"></i>
  <%= f.text_field :email, :class => 'form-control', :style => 'max-width: 300px; margin-left:16px' %> <br><br>
  <%= f.label :password, 'Password', :html => {:class => 'control-label'}, :style => 'font-size: 18px; margin-left: 16px' %> <i class="fa fa-lg fa-star bg bg-warning"></i>
  <%= f.password_field :password, :class => 'form-control', :style => 'max-width: 300px; margin-left:16px' %> <br><br>
  <%= f.label :about, 'About me', :html => {:class => 'control-label'}, :style => 'font-size: 18px; margin-left: 16px' %>
  <%= f.text_area :about, :class => 'form-control', :style => 'max-width: 300px; margin-left:16px' %>
  <hr>
  <%= f.submit :style => 'font-size: 18px; margin-left: 16px', :class => 'btn btn-success' %>
<% end %>

app/views/users/show.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">- WhiteBoard-Central -</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
  <%= form_tag(search_users_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Users" %>
      <button class="btn" type="submit"><i class="fa fa-lg fa-search"></i></button>
    </div>
  <% end %>
                </li>
                <li>
                <%= link_to '- Public Boards -', public_boards_path %>
                </li>
                <li>
                    <%= link_to '- Profile -', users_path + "/" + current_user.id.to_s %>
                </li>
                <li>
                    <%= link_to '- Logout -', logout_path %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

    <% if current_user == User.find(params[:id]) %>
    <!-- Create New Board -->
    <div class="row">
        <div class="text-center col-lg-12">
          <a href="/boards/new">
            <button class="btn btn-lg btn-success">
              Create New Board <i class="fa fa-lg fa-file-picture-o"></i>
            </button>
          </a>
        <%= form_tag(search_boards_path, :method => "get", class: "navbar-form", id: "search-form") do %>
          <div class="input-append">
            <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Boards" %>
            <button class="btn" type="submit"><i class="fa fa-lg fa-search"></i></button>
          </div>
        <% end %>
        </div>
    </div>
    <!-- /.row -->
<hr>
  <% end %>
<!-- Page Content -->
<div class="container">

    <!-- Page Heading -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
              The Board Collection of <%= User.find(session[:user_id]).name %>
            </h1>
        </div>
    </div>
    <!-- /.row -->


    <!-- For Each Board -->
    <% @user.boards.reverse.each do |b| %>
    <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img src=''>
                <%= image_tag b.title.to_s, class:"img-responsive img-thumbnail" %>
            </a>
        </div>
    <!-- Set Privacy Here -->
        <% if current_user == User.find(params[:id]) or b.private == false %>
        <div class="col-md-5">
            <a class="btn btn-md btn-primary" href=<%= '/boards/'+ b.id.to_s + '/edit' %>>Edit Board <div class="fa fa-lg fa-paint-brush"></div></a><br></br>
        <% end  %>
        <% if current_user == User.find(params[:id]) %>
            <div class="button_delete"><%= button_to "Delete Board", boards_destroy_path(b), data: { confirm:'Are you sure you want to delete this Board?'}, method: :delete, remote:true, :id => "button_delete", :class => "btn btn-md btn-danger"%></div><br>
            <%= link_to (b.private ? "Make Public?":"Make Private?"), make_board_private_path(b), :class => "btn btn-md btn-warning" %><br><br>
            <%= link_to 'Update Tags', update_board_info_path(b.id), :class => "btn btn-md btn-success" %>
        <% end  %>
        </div>
    </div>

    <hr>
    <% end %>

 <!-- Pagination -->
<div class="row text-center">
    <div class="col-lg-12">
        <ul class="pagination">
            <li>
                <a href="#">&laquo;</a>
            </li>
            <li class="active">
                <a href="#">1</a>
            </li>
            <li>
                <a href="#">2</a>
            </li>
            <li>
                <a href="#">3</a>
            </li>
            <li>
                <a href="#">4</a>
            </li>
            <li>
                <a href="#">5</a>
            </li>
            <li>
                <a href="#">&raquo;</a>
            </li>
        </ul>
    </div>
</div>
<!-- Footer -->
<footer>
<div class="row">
  <div class="col-lg-12">
          </div>
      </div>
      <!-- /.row -->
  </footer>
<script>
$(document).ready(function(){
  $('.button_delete :input').on('click',this,function(){
    window.location.reload()
    console.log('delete action fired')
  })
})
</script>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>